minimumReleaseAge: 4320
minimumReleaseAgeStrict: true
packages:
  - packages/*
overrides:
  dompurify: 3.4.14
allowBuilds:
  "@google/genai": true
  esbuild: true
  msgpackr-extract: false
  msw: true
  protobufjs: true
