// Distinguishes what a person typed from what the harness injected.
//
// Both agents record injected context with role "user": slash-command
// expansions, skill preambles, subagent task notifications, system reminders and
// continuation nudges. Counting those as user turns buried the four real requests
// of one observed session among twelve "turns", which defeats the overview.
//
// The rule is deliberately conservative, because a false positive hides
// something the user actually wrote: only a *leading* markup tag counts, plus a
// closed list of literal prefixes the harnesses emit.

const LEADING_TAG = /^<[a-z][a-z0-9-]*>/i;

const INJECTED_PREFIXES = [
  "base directory for this skill:",
  "[your previous response had no visible output",
  "no response requested.",
  "caveat: the messages below were generated by the user while running local commands",
];

export function isSyntheticUserText(text: string): boolean {
  const trimmed = text.trimStart();
  if (!trimmed) return false;
  if (LEADING_TAG.test(trimmed)) return true;
  const lowered = trimmed.toLowerCase();
  return INJECTED_PREFIXES.some((prefix) => lowered.startsWith(prefix));
}
