import { describe, expect, it } from "vitest";

import { isSyntheticUserText } from "./synthetic";

describe("isSyntheticUserText", () => {
  it("treats an injected xml-tagged message as machine-generated", () => {
    // All observed in one real transcript, all recorded with role "user".
    for (const text of [
      "<command-message>pr-review-artifact-v3</command-message> <command-name>/pr</command-name>",
      "<task-notification> <task-id>a64a27fa2f97262d4</task-id> </task-notification>",
      "<system-reminder> The user named this session …",
      "<local-command-stdout></local-command-stdout>",
    ]) {
      expect(isSyntheticUserText(text), text.slice(0, 30)).toBe(true);
    }
  });

  it("recognises the known injected prefixes that carry no tag", () => {
    for (const text of [
      "Base directory for this skill: /Users/ana/.claude/skills/pr-review",
      "[Your previous response had no visible output. Please continue…",
      "No response requested.",
      "Caveat: The messages below were generated by the user while running local commands.",
    ]) {
      expect(isSyntheticUserText(text), text.slice(0, 30)).toBe(true);
    }
  });

  it("keeps a real request written by a person", () => {
    for (const text of [
      "Approach this as the design lead at a small studio",
      "quiero actulizar la revision con los nuevos cambios",
      "comenta inline en github en ingles sobre el hallazgo",
      "add a panel next to notes",
      "fix the failing test",
    ]) {
      expect(isSyntheticUserText(text), text.slice(0, 30)).toBe(false);
    }
  });

  it("does not mistake prose that merely mentions a tag or bracket", () => {
    // A person legitimately writes about markup, so only a *leading* tag counts.
    for (const text of [
      "the <div> wrapper is wrong",
      "use <system-reminder> as the marker name",
      "[wip] rebase onto develop",
      "compare a < b and c > d",
    ]) {
      expect(isSyntheticUserText(text), text.slice(0, 30)).toBe(false);
    }
  });

  it("ignores leading whitespace before deciding", () => {
    expect(isSyntheticUserText("   <task-notification> x")).toBe(true);
  });

  it("treats an empty message as not synthetic, so it is still counted", () => {
    expect(isSyntheticUserText("")).toBe(false);
    expect(isSyntheticUserText("   ")).toBe(false);
  });
});
