// Distinguishes what a person typed from what the harness injected.
//
// Both agents record injected context with role "user": slash-command
// expansions, skill preambles, subagent task notifications, system reminders and
// continuation nudges. Counting those as user turns buried the four real requests
// of one observed session among twelve "turns", which defeats the overview.
//
// The rule is deliberately conservative, because a false positive hides
// something the user actually wrote: only a *leading* markup tag counts, plus a
// closed list of literal prefixes the harnesses emit.

const LEADING_TAG = /^<[a-z][a-z0-9-]*>/i;

/**
 * Tags that wrap something the *user* did, not something the harness injected.
 *
 * `!git status` typed at the prompt is recorded as `<bash-input>`; it is a turn a
 * person took and must stay a milestone. Its `<bash-stdout>` counterpart is
 * output and stays collapsed.
 */
const USER_INITIATED_TAGS = new Set(["bash-input"]);

const INJECTED_PREFIXES = [
  "base directory for this skill:",
  "[your previous response had no visible output",
  "no response requested.",
  "caveat: the messages below were generated by the user while running local commands",
];

export function isSyntheticUserText(text: string): boolean {
  const trimmed = text.trimStart();
  if (!trimmed) return false;
  const tag = trimmed.match(LEADING_TAG);
  if (tag) return !USER_INITIATED_TAGS.has(tag[0].slice(1, -1).toLowerCase());
  const lowered = trimmed.toLowerCase();
  return INJECTED_PREFIXES.some((prefix) => lowered.startsWith(prefix));
}
